const githubResult = """
{
  "total_count": 15298,
  "incomplete_results": false,
  "items": [
    {
      "login": "elias",
      "id": 20112,
      "node_id": "MDQ6VXNlcjIwMTEy",
      "avatar_url": "https://avatars.githubusercontent.com/u/20112?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/elias",
      "html_url": "https://github.com/elias",
      "followers_url": "https://api.github.com/users/elias/followers",
      "following_url": "https://api.github.com/users/elias/following{/other_user}",
      "gists_url": "https://api.github.com/users/elias/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/elias/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/elias/subscriptions",
      "organizations_url": "https://api.github.com/users/elias/orgs",
      "repos_url": "https://api.github.com/users/elias/repos",
      "events_url": "https://api.github.com/users/elias/events{/privacy}",
      "received_events_url": "https://api.github.com/users/elias/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "eliasnogueira",
      "id": 284888,
      "node_id": "MDQ6VXNlcjI4NDg4OA==",
      "avatar_url": "https://avatars.githubusercontent.com/u/284888?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/eliasnogueira",
      "html_url": "https://github.com/eliasnogueira",
      "followers_url": "https://api.github.com/users/eliasnogueira/followers",
      "following_url": "https://api.github.com/users/eliasnogueira/following{/other_user}",
      "gists_url": "https://api.github.com/users/eliasnogueira/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/eliasnogueira/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/eliasnogueira/subscriptions",
      "organizations_url": "https://api.github.com/users/eliasnogueira/orgs",
      "repos_url": "https://api.github.com/users/eliasnogueira/repos",
      "events_url": "https://api.github.com/users/eliasnogueira/events{/privacy}",
      "received_events_url": "https://api.github.com/users/eliasnogueira/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "EliasGcf",
      "id": 50633599,
      "node_id": "MDQ6VXNlcjUwNjMzNTk5",
      "avatar_url": "https://avatars.githubusercontent.com/u/50633599?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/EliasGcf",
      "html_url": "https://github.com/EliasGcf",
      "followers_url": "https://api.github.com/users/EliasGcf/followers",
      "following_url": "https://api.github.com/users/EliasGcf/following{/other_user}",
      "gists_url": "https://api.github.com/users/EliasGcf/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/EliasGcf/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/EliasGcf/subscriptions",
      "organizations_url": "https://api.github.com/users/EliasGcf/orgs",
      "repos_url": "https://api.github.com/users/EliasGcf/repos",
      "events_url": "https://api.github.com/users/EliasGcf/events{/privacy}",
      "received_events_url": "https://api.github.com/users/EliasGcf/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "eliasdorneles",
      "id": 37565,
      "node_id": "MDQ6VXNlcjM3NTY1",
      "avatar_url": "https://avatars.githubusercontent.com/u/37565?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/eliasdorneles",
      "html_url": "https://github.com/eliasdorneles",
      "followers_url": "https://api.github.com/users/eliasdorneles/followers",
      "following_url": "https://api.github.com/users/eliasdorneles/following{/other_user}",
      "gists_url": "https://api.github.com/users/eliasdorneles/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/eliasdorneles/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/eliasdorneles/subscriptions",
      "organizations_url": "https://api.github.com/users/eliasdorneles/orgs",
      "repos_url": "https://api.github.com/users/eliasdorneles/repos",
      "events_url": "https://api.github.com/users/eliasdorneles/events{/privacy}",
      "received_events_url": "https://api.github.com/users/eliasdorneles/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "EliasKotlyar",
      "id": 9529505,
      "node_id": "MDQ6VXNlcjk1Mjk1MDU=",
      "avatar_url": "https://avatars.githubusercontent.com/u/9529505?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/EliasKotlyar",
      "html_url": "https://github.com/EliasKotlyar",
      "followers_url": "https://api.github.com/users/EliasKotlyar/followers",
      "following_url": "https://api.github.com/users/EliasKotlyar/following{/other_user}",
      "gists_url": "https://api.github.com/users/EliasKotlyar/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/EliasKotlyar/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/EliasKotlyar/subscriptions",
      "organizations_url": "https://api.github.com/users/EliasKotlyar/orgs",
      "repos_url": "https://api.github.com/users/EliasKotlyar/repos",
      "events_url": "https://api.github.com/users/EliasKotlyar/events{/privacy}",
      "received_events_url": "https://api.github.com/users/EliasKotlyar/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "eliasnaur",
      "id": 524812,
      "node_id": "MDQ6VXNlcjUyNDgxMg==",
      "avatar_url": "https://avatars.githubusercontent.com/u/524812?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/eliasnaur",
      "html_url": "https://github.com/eliasnaur",
      "followers_url": "https://api.github.com/users/eliasnaur/followers",
      "following_url": "https://api.github.com/users/eliasnaur/following{/other_user}",
      "gists_url": "https://api.github.com/users/eliasnaur/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/eliasnaur/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/eliasnaur/subscriptions",
      "organizations_url": "https://api.github.com/users/eliasnaur/orgs",
      "repos_url": "https://api.github.com/users/eliasnaur/repos",
      "events_url": "https://api.github.com/users/eliasnaur/events{/privacy}",
      "received_events_url": "https://api.github.com/users/eliasnaur/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "ejmg",
      "id": 18218174,
      "node_id": "MDQ6VXNlcjE4MjE4MTc0",
      "avatar_url": "https://avatars.githubusercontent.com/u/18218174?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/ejmg",
      "html_url": "https://github.com/ejmg",
      "followers_url": "https://api.github.com/users/ejmg/followers",
      "following_url": "https://api.github.com/users/ejmg/following{/other_user}",
      "gists_url": "https://api.github.com/users/ejmg/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/ejmg/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/ejmg/subscriptions",
      "organizations_url": "https://api.github.com/users/ejmg/orgs",
      "repos_url": "https://api.github.com/users/ejmg/repos",
      "events_url": "https://api.github.com/users/ejmg/events{/privacy}",
      "received_events_url": "https://api.github.com/users/ejmg/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "eliasdaler",
      "id": 1285136,
      "node_id": "MDQ6VXNlcjEyODUxMzY=",
      "avatar_url": "https://avatars.githubusercontent.com/u/1285136?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/eliasdaler",
      "html_url": "https://github.com/eliasdaler",
      "followers_url": "https://api.github.com/users/eliasdaler/followers",
      "following_url": "https://api.github.com/users/eliasdaler/following{/other_user}",
      "gists_url": "https://api.github.com/users/eliasdaler/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/eliasdaler/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/eliasdaler/subscriptions",
      "organizations_url": "https://api.github.com/users/eliasdaler/orgs",
      "repos_url": "https://api.github.com/users/eliasdaler/repos",
      "events_url": "https://api.github.com/users/eliasdaler/events{/privacy}",
      "received_events_url": "https://api.github.com/users/eliasdaler/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "eliasyaoyc",
      "id": 46013886,
      "node_id": "MDQ6VXNlcjQ2MDEzODg2",
      "avatar_url": "https://avatars.githubusercontent.com/u/46013886?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/eliasyaoyc",
      "html_url": "https://github.com/eliasyaoyc",
      "followers_url": "https://api.github.com/users/eliasyaoyc/followers",
      "following_url": "https://api.github.com/users/eliasyaoyc/following{/other_user}",
      "gists_url": "https://api.github.com/users/eliasyaoyc/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/eliasyaoyc/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/eliasyaoyc/subscriptions",
      "organizations_url": "https://api.github.com/users/eliasyaoyc/orgs",
      "repos_url": "https://api.github.com/users/eliasyaoyc/repos",
      "events_url": "https://api.github.com/users/eliasyaoyc/events{/privacy}",
      "received_events_url": "https://api.github.com/users/eliasyaoyc/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "elrumo",
      "id": 36299870,
      "node_id": "MDQ6VXNlcjM2Mjk5ODcw",
      "avatar_url": "https://avatars.githubusercontent.com/u/36299870?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/elrumo",
      "html_url": "https://github.com/elrumo",
      "followers_url": "https://api.github.com/users/elrumo/followers",
      "following_url": "https://api.github.com/users/elrumo/following{/other_user}",
      "gists_url": "https://api.github.com/users/elrumo/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/elrumo/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/elrumo/subscriptions",
      "organizations_url": "https://api.github.com/users/elrumo/orgs",
      "repos_url": "https://api.github.com/users/elrumo/repos",
      "events_url": "https://api.github.com/users/elrumo/events{/privacy}",
      "received_events_url": "https://api.github.com/users/elrumo/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "eliasdabbas",
      "id": 15708966,
      "node_id": "MDQ6VXNlcjE1NzA4OTY2",
      "avatar_url": "https://avatars.githubusercontent.com/u/15708966?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/eliasdabbas",
      "html_url": "https://github.com/eliasdabbas",
      "followers_url": "https://api.github.com/users/eliasdabbas/followers",
      "following_url": "https://api.github.com/users/eliasdabbas/following{/other_user}",
      "gists_url": "https://api.github.com/users/eliasdabbas/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/eliasdabbas/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/eliasdabbas/subscriptions",
      "organizations_url": "https://api.github.com/users/eliasdabbas/orgs",
      "repos_url": "https://api.github.com/users/eliasdabbas/repos",
      "events_url": "https://api.github.com/users/eliasdabbas/events{/privacy}",
      "received_events_url": "https://api.github.com/users/eliasdabbas/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "eliaswalyba",
      "id": 19255763,
      "node_id": "MDQ6VXNlcjE5MjU1NzYz",
      "avatar_url": "https://avatars.githubusercontent.com/u/19255763?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/eliaswalyba",
      "html_url": "https://github.com/eliaswalyba",
      "followers_url": "https://api.github.com/users/eliaswalyba/followers",
      "following_url": "https://api.github.com/users/eliaswalyba/following{/other_user}",
      "gists_url": "https://api.github.com/users/eliaswalyba/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/eliaswalyba/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/eliaswalyba/subscriptions",
      "organizations_url": "https://api.github.com/users/eliaswalyba/orgs",
      "repos_url": "https://api.github.com/users/eliaswalyba/repos",
      "events_url": "https://api.github.com/users/eliaswalyba/events{/privacy}",
      "received_events_url": "https://api.github.com/users/eliaswalyba/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "lykmapipo",
      "id": 1610857,
      "node_id": "MDQ6VXNlcjE2MTA4NTc=",
      "avatar_url": "https://avatars.githubusercontent.com/u/1610857?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/lykmapipo",
      "html_url": "https://github.com/lykmapipo",
      "followers_url": "https://api.github.com/users/lykmapipo/followers",
      "following_url": "https://api.github.com/users/lykmapipo/following{/other_user}",
      "gists_url": "https://api.github.com/users/lykmapipo/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/lykmapipo/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/lykmapipo/subscriptions",
      "organizations_url": "https://api.github.com/users/lykmapipo/orgs",
      "repos_url": "https://api.github.com/users/lykmapipo/repos",
      "events_url": "https://api.github.com/users/lykmapipo/events{/privacy}",
      "received_events_url": "https://api.github.com/users/lykmapipo/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "EliasGabriel1",
      "id": 50595684,
      "node_id": "MDQ6VXNlcjUwNTk1Njg0",
      "avatar_url": "https://avatars.githubusercontent.com/u/50595684?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/EliasGabriel1",
      "html_url": "https://github.com/EliasGabriel1",
      "followers_url": "https://api.github.com/users/EliasGabriel1/followers",
      "following_url": "https://api.github.com/users/EliasGabriel1/following{/other_user}",
      "gists_url": "https://api.github.com/users/EliasGabriel1/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/EliasGabriel1/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/EliasGabriel1/subscriptions",
      "organizations_url": "https://api.github.com/users/EliasGabriel1/orgs",
      "repos_url": "https://api.github.com/users/EliasGabriel1/repos",
      "events_url": "https://api.github.com/users/EliasGabriel1/events{/privacy}",
      "received_events_url": "https://api.github.com/users/EliasGabriel1/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "eliasreis54",
      "id": 29265526,
      "node_id": "MDQ6VXNlcjI5MjY1NTI2",
      "avatar_url": "https://avatars.githubusercontent.com/u/29265526?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/eliasreis54",
      "html_url": "https://github.com/eliasreis54",
      "followers_url": "https://api.github.com/users/eliasreis54/followers",
      "following_url": "https://api.github.com/users/eliasreis54/following{/other_user}",
      "gists_url": "https://api.github.com/users/eliasreis54/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/eliasreis54/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/eliasreis54/subscriptions",
      "organizations_url": "https://api.github.com/users/eliasreis54/orgs",
      "repos_url": "https://api.github.com/users/eliasreis54/repos",
      "events_url": "https://api.github.com/users/eliasreis54/events{/privacy}",
      "received_events_url": "https://api.github.com/users/eliasreis54/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "eliassjogreen",
      "id": 19556658,
      "node_id": "MDQ6VXNlcjE5NTU2NjU4",
      "avatar_url": "https://avatars.githubusercontent.com/u/19556658?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/eliassjogreen",
      "html_url": "https://github.com/eliassjogreen",
      "followers_url": "https://api.github.com/users/eliassjogreen/followers",
      "following_url": "https://api.github.com/users/eliassjogreen/following{/other_user}",
      "gists_url": "https://api.github.com/users/eliassjogreen/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/eliassjogreen/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/eliassjogreen/subscriptions",
      "organizations_url": "https://api.github.com/users/eliassjogreen/orgs",
      "repos_url": "https://api.github.com/users/eliassjogreen/repos",
      "events_url": "https://api.github.com/users/eliassjogreen/events{/privacy}",
      "received_events_url": "https://api.github.com/users/eliassjogreen/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "eliascarv",
      "id": 73039601,
      "node_id": "MDQ6VXNlcjczMDM5NjAx",
      "avatar_url": "https://avatars.githubusercontent.com/u/73039601?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/eliascarv",
      "html_url": "https://github.com/eliascarv",
      "followers_url": "https://api.github.com/users/eliascarv/followers",
      "following_url": "https://api.github.com/users/eliascarv/following{/other_user}",
      "gists_url": "https://api.github.com/users/eliascarv/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/eliascarv/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/eliascarv/subscriptions",
      "organizations_url": "https://api.github.com/users/eliascarv/orgs",
      "repos_url": "https://api.github.com/users/eliascarv/repos",
      "events_url": "https://api.github.com/users/eliascarv/events{/privacy}",
      "received_events_url": "https://api.github.com/users/eliascarv/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "eliasah",
      "id": 2973143,
      "node_id": "MDQ6VXNlcjI5NzMxNDM=",
      "avatar_url": "https://avatars.githubusercontent.com/u/2973143?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/eliasah",
      "html_url": "https://github.com/eliasah",
      "followers_url": "https://api.github.com/users/eliasah/followers",
      "following_url": "https://api.github.com/users/eliasah/following{/other_user}",
      "gists_url": "https://api.github.com/users/eliasah/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/eliasah/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/eliasah/subscriptions",
      "organizations_url": "https://api.github.com/users/eliasah/orgs",
      "repos_url": "https://api.github.com/users/eliasah/repos",
      "events_url": "https://api.github.com/users/eliasah/events{/privacy}",
      "received_events_url": "https://api.github.com/users/eliasah/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "EliasMurat",
      "id": 65032290,
      "node_id": "MDQ6VXNlcjY1MDMyMjkw",
      "avatar_url": "https://avatars.githubusercontent.com/u/65032290?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/EliasMurat",
      "html_url": "https://github.com/EliasMurat",
      "followers_url": "https://api.github.com/users/EliasMurat/followers",
      "following_url": "https://api.github.com/users/EliasMurat/following{/other_user}",
      "gists_url": "https://api.github.com/users/EliasMurat/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/EliasMurat/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/EliasMurat/subscriptions",
      "organizations_url": "https://api.github.com/users/EliasMurat/orgs",
      "repos_url": "https://api.github.com/users/EliasMurat/repos",
      "events_url": "https://api.github.com/users/EliasMurat/events{/privacy}",
      "received_events_url": "https://api.github.com/users/EliasMurat/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "eliascodes",
      "id": 12719553,
      "node_id": "MDQ6VXNlcjEyNzE5NTUz",
      "avatar_url": "https://avatars.githubusercontent.com/u/12719553?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/eliascodes",
      "html_url": "https://github.com/eliascodes",
      "followers_url": "https://api.github.com/users/eliascodes/followers",
      "following_url": "https://api.github.com/users/eliascodes/following{/other_user}",
      "gists_url": "https://api.github.com/users/eliascodes/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/eliascodes/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/eliascodes/subscriptions",
      "organizations_url": "https://api.github.com/users/eliascodes/orgs",
      "repos_url": "https://api.github.com/users/eliascodes/repos",
      "events_url": "https://api.github.com/users/eliascodes/events{/privacy}",
      "received_events_url": "https://api.github.com/users/eliascodes/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "eliaskousk",
      "id": 801988,
      "node_id": "MDQ6VXNlcjgwMTk4OA==",
      "avatar_url": "https://avatars.githubusercontent.com/u/801988?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/eliaskousk",
      "html_url": "https://github.com/eliaskousk",
      "followers_url": "https://api.github.com/users/eliaskousk/followers",
      "following_url": "https://api.github.com/users/eliaskousk/following{/other_user}",
      "gists_url": "https://api.github.com/users/eliaskousk/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/eliaskousk/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/eliaskousk/subscriptions",
      "organizations_url": "https://api.github.com/users/eliaskousk/orgs",
      "repos_url": "https://api.github.com/users/eliaskousk/repos",
      "events_url": "https://api.github.com/users/eliaskousk/events{/privacy}",
      "received_events_url": "https://api.github.com/users/eliaskousk/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "eliasp",
      "id": 48491,
      "node_id": "MDQ6VXNlcjQ4NDkx",
      "avatar_url": "https://avatars.githubusercontent.com/u/48491?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/eliasp",
      "html_url": "https://github.com/eliasp",
      "followers_url": "https://api.github.com/users/eliasp/followers",
      "following_url": "https://api.github.com/users/eliasp/following{/other_user}",
      "gists_url": "https://api.github.com/users/eliasp/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/eliasp/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/eliasp/subscriptions",
      "organizations_url": "https://api.github.com/users/eliasp/orgs",
      "repos_url": "https://api.github.com/users/eliasp/repos",
      "events_url": "https://api.github.com/users/eliasp/events{/privacy}",
      "received_events_url": "https://api.github.com/users/eliasp/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "EliasVansteenkiste",
      "id": 2494383,
      "node_id": "MDQ6VXNlcjI0OTQzODM=",
      "avatar_url": "https://avatars.githubusercontent.com/u/2494383?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/EliasVansteenkiste",
      "html_url": "https://github.com/EliasVansteenkiste",
      "followers_url": "https://api.github.com/users/EliasVansteenkiste/followers",
      "following_url": "https://api.github.com/users/EliasVansteenkiste/following{/other_user}",
      "gists_url": "https://api.github.com/users/EliasVansteenkiste/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/EliasVansteenkiste/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/EliasVansteenkiste/subscriptions",
      "organizations_url": "https://api.github.com/users/EliasVansteenkiste/orgs",
      "repos_url": "https://api.github.com/users/EliasVansteenkiste/repos",
      "events_url": "https://api.github.com/users/EliasVansteenkiste/events{/privacy}",
      "received_events_url": "https://api.github.com/users/EliasVansteenkiste/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "eliasjpr",
      "id": 1685772,
      "node_id": "MDQ6VXNlcjE2ODU3NzI=",
      "avatar_url": "https://avatars.githubusercontent.com/u/1685772?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/eliasjpr",
      "html_url": "https://github.com/eliasjpr",
      "followers_url": "https://api.github.com/users/eliasjpr/followers",
      "following_url": "https://api.github.com/users/eliasjpr/following{/other_user}",
      "gists_url": "https://api.github.com/users/eliasjpr/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/eliasjpr/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/eliasjpr/subscriptions",
      "organizations_url": "https://api.github.com/users/eliasjpr/orgs",
      "repos_url": "https://api.github.com/users/eliasjpr/repos",
      "events_url": "https://api.github.com/users/eliasjpr/events{/privacy}",
      "received_events_url": "https://api.github.com/users/eliasjpr/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "eliast",
      "id": 26843,
      "node_id": "MDQ6VXNlcjI2ODQz",
      "avatar_url": "https://avatars.githubusercontent.com/u/26843?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/eliast",
      "html_url": "https://github.com/eliast",
      "followers_url": "https://api.github.com/users/eliast/followers",
      "following_url": "https://api.github.com/users/eliast/following{/other_user}",
      "gists_url": "https://api.github.com/users/eliast/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/eliast/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/eliast/subscriptions",
      "organizations_url": "https://api.github.com/users/eliast/orgs",
      "repos_url": "https://api.github.com/users/eliast/repos",
      "events_url": "https://api.github.com/users/eliast/events{/privacy}",
      "received_events_url": "https://api.github.com/users/eliast/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "SanderElias",
      "id": 1249083,
      "node_id": "MDQ6VXNlcjEyNDkwODM=",
      "avatar_url": "https://avatars.githubusercontent.com/u/1249083?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/SanderElias",
      "html_url": "https://github.com/SanderElias",
      "followers_url": "https://api.github.com/users/SanderElias/followers",
      "following_url": "https://api.github.com/users/SanderElias/following{/other_user}",
      "gists_url": "https://api.github.com/users/SanderElias/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/SanderElias/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/SanderElias/subscriptions",
      "organizations_url": "https://api.github.com/users/SanderElias/orgs",
      "repos_url": "https://api.github.com/users/SanderElias/repos",
      "events_url": "https://api.github.com/users/SanderElias/events{/privacy}",
      "received_events_url": "https://api.github.com/users/SanderElias/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "eliasngumbi998",
      "id": 32370330,
      "node_id": "MDQ6VXNlcjMyMzcwMzMw",
      "avatar_url": "https://avatars.githubusercontent.com/u/32370330?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/eliasngumbi998",
      "html_url": "https://github.com/eliasngumbi998",
      "followers_url": "https://api.github.com/users/eliasngumbi998/followers",
      "following_url": "https://api.github.com/users/eliasngumbi998/following{/other_user}",
      "gists_url": "https://api.github.com/users/eliasngumbi998/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/eliasngumbi998/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/eliasngumbi998/subscriptions",
      "organizations_url": "https://api.github.com/users/eliasngumbi998/orgs",
      "repos_url": "https://api.github.com/users/eliasngumbi998/repos",
      "events_url": "https://api.github.com/users/eliasngumbi998/events{/privacy}",
      "received_events_url": "https://api.github.com/users/eliasngumbi998/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "elias8",
      "id": 18151864,
      "node_id": "MDQ6VXNlcjE4MTUxODY0",
      "avatar_url": "https://avatars.githubusercontent.com/u/18151864?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/elias8",
      "html_url": "https://github.com/elias8",
      "followers_url": "https://api.github.com/users/elias8/followers",
      "following_url": "https://api.github.com/users/elias8/following{/other_user}",
      "gists_url": "https://api.github.com/users/elias8/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/elias8/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/elias8/subscriptions",
      "organizations_url": "https://api.github.com/users/elias8/orgs",
      "repos_url": "https://api.github.com/users/elias8/repos",
      "events_url": "https://api.github.com/users/elias8/events{/privacy}",
      "received_events_url": "https://api.github.com/users/elias8/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "limneos",
      "id": 239807,
      "node_id": "MDQ6VXNlcjIzOTgwNw==",
      "avatar_url": "https://avatars.githubusercontent.com/u/239807?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/limneos",
      "html_url": "https://github.com/limneos",
      "followers_url": "https://api.github.com/users/limneos/followers",
      "following_url": "https://api.github.com/users/limneos/following{/other_user}",
      "gists_url": "https://api.github.com/users/limneos/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/limneos/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/limneos/subscriptions",
      "organizations_url": "https://api.github.com/users/limneos/orgs",
      "repos_url": "https://api.github.com/users/limneos/repos",
      "events_url": "https://api.github.com/users/limneos/events{/privacy}",
      "received_events_url": "https://api.github.com/users/limneos/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "EliasFarhan",
      "id": 2393882,
      "node_id": "MDQ6VXNlcjIzOTM4ODI=",
      "avatar_url": "https://avatars.githubusercontent.com/u/2393882?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/EliasFarhan",
      "html_url": "https://github.com/EliasFarhan",
      "followers_url": "https://api.github.com/users/EliasFarhan/followers",
      "following_url": "https://api.github.com/users/EliasFarhan/following{/other_user}",
      "gists_url": "https://api.github.com/users/EliasFarhan/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/EliasFarhan/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/EliasFarhan/subscriptions",
      "organizations_url": "https://api.github.com/users/EliasFarhan/orgs",
      "repos_url": "https://api.github.com/users/EliasFarhan/repos",
      "events_url": "https://api.github.com/users/EliasFarhan/events{/privacy}",
      "received_events_url": "https://api.github.com/users/EliasFarhan/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    }
  ]
}

""";
